### ISSUE TITLE
Increase the pre-commit auto-update frequency

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/scikit-hep-testdata#116]
Quarterly is too infrequent. People usually assume MyPy isn't that old, things sometimes break, etc. Monthly is the least recent I think I'd be confortble with. In #114, two things had broken in the last quarter.

https://github.com/scikit-hep/scikit-hep-testdata/blob/c0e2ed9cc7f738f93edb77098cdb3e93b6cd6896/.pre-commit-config.yaml#L3

**Comment by eduardo-rodrigues** [comment]
Agreed. Let's make it monthly as in many other packages ... Done via https://github.com/scikit-hep/scikit-hep-testdata/pull/117.
