### ISSUE TITLE
Seems like there are duplicate files

### ISSUE THREAD

**Issue by ariostas** [scikit-hep/scikit-hep-testdata#143]
The `test_ntuple_*` files seem to play the same role as the `uproot_ntuple_*` files. They might not be exact duplicates since the `uproot_ntuple_*` files most likely use a later RNTuple version, but I don't think it makes sense to keep both sets given that the RNTuple spec is not stable yet. Should I remove the `uproot_ntuple_*` ones and update the `test_ntuple_*` ones to RNTuple RC2?

**Comment by Moelf** [comment]
yeah indeed, anything pre-RC2 can be dropped. Basically, for RNTuple, anything before the formal version 2 release will be neither forward nor backward compatible, so there's no point in supporting multiple versions and thus no point in keeping multiple versions of test data

**Comment by jpivarski** [comment]
I concur: it would just be confusing to have old RNTuple files there, unless the filename very clearly indicated the range of validity. However, RNTuple has no backward compatibility until 1.0 and will have very strong backward compatibility thereafter, so even maintaining well-labeled versions doesn't make much sense.
