### ISSUE TITLE
Include files from uproot's github pages

### ISSUE THREAD

**Issue by benkrikler** [scikit-hep/scikit-hep-testdata#16]
To help uproot make full use of this package, we would need to incorporate the ROOT files from its github pages as well.

@jpivarski 's comment via email:

>  I'll need to move some new files into scikit-hep-testdata to fully move over. These will come from the gh-pages branch of uproot:
>
>  https://github.com/scikit-hep/uproot/tree/gh-pages/examples
>
> which maps names like Event.root (60 MB! can't fit in PyPI repo!) to web URLs: http://scikit-hep.org/uproot/examples/Event.root, etc.

For files that can't fit into pypi, we probably need to resort to the discussion from #3.

**Comment by benkrikler** [comment]
On the specific Event.root file you mention, @jpivarski, I wonder if we already contain some version of that: https://github.com/scikit-hep/scikit-hep-testdata/blob/master/skhep_testdata/data/uproot-Event.root.  The git log (with `--follow`) says it was added to uproot by commit 34deec50db1ed5a48c0d4600a5150fb999b34a6b

**Comment by jpivarski** [comment]
I received a pull request that increases the interpreted types in uproot, but adds more types and more data to Event.root, blowing it up from 30 MB to 60 MB. I wanted to accept the work on uproot's interpretations, so I took the bigger Event.root as well. The version in uproot's gh-pages branch is the new one. (I had to go and replace the old one everywhere.)

**Comment by eduardo-rodrigues** [comment]
This package allows retrieval of files with HTTP. For files too big for deployment on PyPI we would use the scikit-hep.org site, have a directory there *only* for big testdata … and problem solved. Seems neat and simple to me. On top of that, the files are still kept within the org, so easily traceable and maintained/updated by us. What do you think? Event.root could be a first entry file.

**Comment by jpivarski** [comment]
Event.root is already under scikit-hep.org, as

http://scikit-hep.org/uproot/examples/Event.root

because it's in uproot's gh-pages branch. (GtiHub does that automatically.) But perhaps you mean a directory controlled by scikit-hep-testdata? I'd be up for more consolidation.

**Comment by eduardo-rodrigues** [comment]
Ah, yes, @jpivarski, I forgot that.

It would make sense to have a test data directory controlled in some way by scikit-hep-testdata, yes. How precisely to do this, I don't have a full idea yet. But yes, I should have been clearer, sorry.

**Comment by jpivarski** [comment]
You can make your own gh-pages branch. Every directory/file "d/f.xyz" in that branch will be presented as

http://scikit-hep.org/scikit-hep-testdata/d/f.xyz

**Comment by eduardo-rodrigues** [comment]
Thanks.

**Comment by eduardo-rodrigues** [comment]
@jpivarski, @henryiii, I think we can safely close this issue given https://github.com/scikit-hep/scikit-hep-testdata/issues/48, right?

**Comment by jpivarski** [comment]
The specific file @benkrikler was talking about is still not on scikit-hep-testdata. There are two versions of it; ROOT _makes_ it as part of its unit tests, and it can be made in different ways, depending on some parameters. A test in Uproot 3 had to rewrite the file, and I moved it out of Uproot because it was starting to get too big for that: 36 MB. Under the new conditions (no files in the PyPI package), 36 MB is not too big.

As a consequence of the Uproot repo name change, the URL for that file has changed (this is the "new" version):

http://scikit-hep.org/uproot3/examples/Event.root

but I'm putting it into scikit-hep-testdata now, so that it's no longer sensitive to such changes.
