### ISSUE TITLE
Import root files from uproot

### ISSUE THREAD

**Issue by benkrikler** [scikit-hep/scikit-hep-testdata#2]
I've spoken with Jim Pivarski and he's happy for us to copy in the root files he's collected in [uproot/tests/samples](https://github.com/scikit-hep/uproot/tree/master/tests/samples).

**Comment by eduardo-rodrigues** [comment]
Quick question: many of the files from @jpivarski have a name that trivially matches issues in `uproot`. How to deal with that in this package? Shall those `issueXX.root` files be named `uproot-issueXX.root` for example? As the "database" grows, would it make sense to have a file where a brief description of what each file is useful for is provided? I realise this is already a fair amount of work for the existing files. But at least for new ones this would be useful as a must-have info in PRs for additions. I believe so. What do you think?

**Comment by benkrikler** [comment]
Yes, this is a really good point.  Ideally I'd like to rename the files from uproot to something more descriptive outside of uproot,  and then add a proper description for each one in, at least in the README.  If I'm honest, I imagine until this is done it's going to be pretty awkward to use this repository fully.

I definitely agree though that for new files we should make such a description a requirement!

**Comment by eduardo-rodrigues** [comment]
OK, great. If you happen to make additions to the package soon, then this is info for the "contributing" section. Thanks.

**Comment by eduardo-rodrigues** [comment]
I think we can close this very old "issue" at this point. FYI @jpivarski.
