### ISSUE TITLE
Are any test files accessible by (public) XRootD?

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/scikit-hep-testdata#21]
I want to add a test for scikit-hep/uproot#242 before merging it, but it's an update to XRootD handling and isn't properly tested unless the file comes over XRootD. Can I find URLs to external test data by protocol?

**Comment by benkrikler** [comment]
At the moment the only option to query our database is by the name of the file as it is within our catalogue.  I could imagine adding options to query by other means, though I'm a little nervous to make things too complicated.  

In any case, the "catalogue" here doesn't know about any xrootd files at this point, though it could be good to add some.  We might need to think about whether they're classed as remote, local, or something new as well.  In any case the local vs remote status is internal to this package: if it's a "remote" file, this package pulls it for you to make it available locally.  In the xrootd case, we wouldn't do this they'd still be served via xrootd, I imagine.  This functionality might also add an xrootd dependency to this package if we need to verify that the path is reachable.  All of this is doable, I'm just thinking aloud (or a-written).

In the meantime, perhaps the CMS nanoaod files Stefan Wunsch helped get public for RDataFrame tutorials would help you: 
 * https://root.cern/doc/master/df102__NanoAODDimuonAnalysis_8C.html
 * https://root.cern/doc/master/df103__NanoAODHiggsAnalysis_8C.html

**Comment by jpivarski** [comment]
Thanks! I was searching the CERN Open Data Portal and found suitable files, but they only expose the HTTP URL on the website (naturally). The XRootD URL is buried in a virtual machine. But these example scripts show the right URL.

**Comment by benkrikler** [comment]
No problem! I guess it's not quite gone through the interface I was trying to provide, but this package has indirectly served it's purpose here at least.

**Comment by sbinet** [comment]
@jpivarski FYI, I am already using the ROOT files mentionned in https://github.com/scikit-hep/scikit-hep-testdata/issues/21#issuecomment-469299349.
My experience is that the EOS+XRootD server has *very* flaky performances: it's not uncommon that (under travis-ci) I get timeouts.
I had to increase the timeouts to 10mn.

(I suspect that eos+xrootd server throttles clients.)

**Comment by eduardo-rodrigues** [comment]
Closing this issue since you @jpivarski mention above that you had found suitable files. Feel free to reopen and update the discussion if I misunderstood the status.
