### ISSUE TITLE
Investigate options for large file storage

### ISSUE THREAD

**Issue by benkrikler** [scikit-hep/scikit-hep-testdata#3]
Storing large files in git repositories can be problematic.  Since this repository is only really intended for testing set-ups it seems not unreasonable to do this but we might be able to work with other options as well.
 1. use git lfs: Need to understand if this can play nicely once the package is installed via pip, away from git
 2. Use existing open-access data solutions.  Cern's opendata platform is very nice, but it's not straightforward to put new files into it.
 3. Jim Pivarski has suggested S3 as a cheaper alternative to DropBox

**Comment by kreczko** [comment]
If EOS had and HTTP front-end (e.g. for eospublic.cern.ch), that would be a possibility as well.

**Comment by kreczko** [comment]
So, short anser to HTTP EOS: it does exist, but
 - https://eospublichttp.cern.ch/eos/: requires X509
 - https://eospublichttp.cern.ch:8443/eos: requires kerberos auth

The only way to get a public instance (no auth) is to request it: https://cern.service-now.com/service-portal/

**Comment by benkrikler** [comment]
I suppose CERN-box might be workable instead though. I think you can download files directly from that (though don't remember the last time I tried).

**Comment by kreczko** [comment]
We now have a first test-instance of an EOS Web page hosting some data:
http://fast-hep-data.web.cern.ch/fast-hep-data/

The only file at the moment: 
 - http://fast-hep-data.web.cern.ch/fast-hep-data/cms/L1T/CMS_L1T_study.root

This space is limited to 1TB for now but still represents a useful amount.

**Comment by eduardo-rodrigues** [comment]
Closing given the discussions, decisions and actions of https://github.com/scikit-hep/scikit-hep-testdata/issues/48. FYI @jpivarski, @henryiii.
