### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/scikit-hep-testdata#30]
Looking at the configuration files, it seems that this should upload a new version to PyPI with every push to master. In fact, when I merged PR #29, it did start a deployment job:

https://github.com/scikit-hep/scikit-hep-testdata/runs/666738965?check_suite_focus=true

But a new version did not show up:

https://pypi.org/project/scikit-hep-testdata/#history

(At least, the last time I looked, the last version was still 0.2.0 from March 9, 2020.)

Should I draft a release?

**Comment by eduardo-rodrigues** [comment]
Hmm, I see that the "dist" step had the deployment skipped whereas all bits for the "PythonX.Y" steps ran fully. I dunno why that is. @henryiii probably will …

If things are stuck I agree we can just deploy the wheels manually.

**Comment by jpivarski** [comment]
What specifically do you mean by "manual"? You mean run twine on my computer?

**Comment by eduardo-rodrigues** [comment]
Yep. It typically takes of order a minute. But it would be good to understand why the automatic deployment isn't working. Did it work for you last time @henryiii ?

**Comment by henryiii** [comment]
No, not every push to master, every GitHub release: https://github.com/scikit-hep/scikit-hep-testdata/releases should have v0.3.0 or v0.2.1 or v0.2.0.post1, something. If you make a GitHub release, the PyPI release will follow a minute or two later.

**Comment by henryiii** [comment]
Just use the GitHub UI, everything else happens for you.

**Comment by henryiii** [comment]
And here's the line that makes sure there's a tag before releasing:

https://github.com/scikit-hep/scikit-hep-testdata/blob/f22a92fd4d8b238c7838df4fe732e1b983e10e4c/.github/workflows/ci.yml#L68

**Comment by eduardo-rodrigues** [comment]
OK, so I made a release but the deployment fails because of a 60 MB limit on PyPI:
`HTTPError: 400 Client Error: File too large. Limit for project 'scikit-hep-testdata' is 60 MB. See https://pypi.org/help/#file-size-limit for url: https://upload.pypi.org/legacy/`.
You can see this message in the CI of the last commit. One can ask PyPI to extend the limit, though …

**Comment by eduardo-rodrigues** [comment]
Some of the files are indeed large, see for example `src/skhep_testdata/data/uproot-issue475b.root` that is considerably larger than the others. I wonder why the test files need to be so large. In principle the technical issue should show up with just a few events?

**Comment by jpivarski** [comment]
I didn't make the test files; I asked for them to be small and not everybody does that. Sorting them all by the number of kilobytes, the biggest ones are

```
4700	src/skhep_testdata/data/uproot-issue63.root
4916	src/skhep_testdata/data/uproot-issue96.root
6996	src/skhep_testdata/data/uproot-issue465-nested.root
8648	src/skhep_testdata/data/uproot-issue475b.root
30636	src/skhep_testdata/data/uproot-Event.root
```

In this tail, issue63.root and issue96.root are used in explicit regression tests. issue465-nested.root and issue475b.root are not because at that time, I decided that they are too large. It's a question of whether the cut-off is 5 MB or something larger than 5 MB...

The one that really sticks out, which would make a big difference toward the 60 MB limit, is Event.root. This one comes from ROOT's own unit tests and has a variety of weird things in an TTree (like TH1F histograms _inside_ the TTree, one per event!). I had removed that one from the Uproot repo, but I think its effect still lingers in the git-clone time. Since then, I've been accessing it through HTTP on github.io, but it's the most likely random failure in Travis tests.

It's too bad because this is a good file for stress-testing, but there isn't a good way to host them.

As an action item, I think you can remove the three files that are above 5 MB: issue465-nested.root, issue475b.root, and Event.root. The last one will drop the package size by a factor of 2 and it would be deployable.

**Comment by henryiii** [comment]
Can't we remote download one from ROOT's testing from wherever ROOT stores it?

Also, given that this is a collection of test files, it might be valid to ask PyPI for a size increase. It's not going to update very often (in theory) and it will not have many different wheels (I currently only have a single wheel and no source).

**Comment by jpivarski** [comment]
> Can't we remote download one from ROOT's testing from wherever ROOT stores it?

Event.root is created by running ROOT's test suite. I'll have to remind myself how to run the ROOT tests and see if I can find the line that sets the number of events. Cutting it down by a factor of 10 would solve everything (I think it has 1000 events).

For now, though, we can get under budget by dropping this one file (which would be to say that our single-file limit is 10 MB?). We can keep open the option of requesting an increase later, if we get into a situation where we have a large number of small files that are all actively used.

(Also, a repo/Python package might not be the best way to deliver this, but the thing I like about it now is that I can decouple the Uproot codebase from the test files, whatever happens to the test file delivery in the future.)

**Comment by eduardo-rodrigues** [comment]
Let's not give up just now and remove things. I'm happy to try and get PyPI to allocated us a bit more space, say go from 60 to 100 MB. I will create the PR later today ...

**Comment by eduardo-rodrigues** [comment]
We have such a large org that requesting a bit more space for a package used by others in the org seems a good approach, so feel positive about the request.

**Comment by eduardo-rodrigues** [comment]
Folks, I went ahead and made the request for an increase of the limit, see issue #382 on pypi-support. Let's see ...

**Comment by benkrikler** [comment]
Hi everyone!

When I started putting this package together I thought this might be a problem.  I set up a (somewhat crude) interface to pull large data files on request, so we didn't have to ship them in the package by default.  Something like git lfs would be a good solution perhaps, but then wrapping this in python, etc, got messy so I went with a similar custom-rolled approach.  My concept for the UI here was to be similar to how [Spacy](https://spacy.io/usage/models) gives an easy way to fetch models and data without shipping with this included in the package.  This interface is still there, but it may be that there's little appetite to use this (in which case, probably better to remove it completely). I think either way large data files needs a bit of thought, because I'm sure this wont be the last time we want to add a "big" file. 

You can see the relevant code in https://github.com/scikit-hep/scikit-hep-testdata/blob/master/src/skhep_testdata/remote_files.py which is configured by `https://github.com/scikit-hep/scikit-hep-testdata/blob/master/src/skhep_testdata/remote_datasets.yml`, in the hope that it would be easier to maintain and extend with new files.

Hosting them is a separate (but related) issue, which I never had any solid thoughts on.

**Comment by henryiii** [comment]
Why is this closed? I don't see a new version up yet.

**Comment by eduardo-rodrigues** [comment]
If the release is urgent we can temporarily remove Event.root, which gets us below the PyPI limit (my issue to PyPI to increase the limit is still pending) and make a release. Then we cal really close this ...

**Comment by jpivarski** [comment]
Isn't 0.3.0 the new version?

**Comment by eduardo-rodrigues** [comment]
It is. But that's the one I saw got refused on PyPI due to the size limit. I guess one can remove the one biggest file and retag; that should retrigger the deployment.

**Comment by jpivarski** [comment]
Right, it's the new one:

```
>>> import skhep_testdata
>>> skhep_testdata.__version__
'0.3.0'
>>> open(skhep_testdata.data_path("uproot-sample-6.20.04-zlib.root"), "rb").read(10)
b'root\x00\x00\xf24\x00\x00'
```

(That 6.20.04 file is one of the ones that were added 7 days ago.)

I thought I had installed it with pip or conda, but apparently I hadn't:

```
% conda list skhep_testdata
# packages in environment at /home/pivarski/miniconda3:
#
# Name                    Version                   Build  Channel
```

So I'll reopen this. Oh, it's already open.

**Comment by eduardo-rodrigues** [comment]
@jpivarski, you can now install 0.3.0 just released. It contains everything *except* `uproot-Event.root`, which we can re-incorporate (would be great) once PyPI relaxes the package size limit.

HTH.

**Comment by henryiii** [comment]
@jpivarski Just look at the badge on the readme - it has the latest PyPI version. Until that changes, a new version has not been released. That's one reason I push for having them :)
