### ISSUE TITLE
Source tarball is missing setup.py, skhep_testdata directory, etc

### ISSUE THREAD

**Issue by veprbl** [scikit-hep/scikit-hep-testdata#60]
```
# wget https://files.pythonhosted.org/packages/7f/85/dc18ef24a92c8989d3884c95b0b3837556df1c7a9960c1cfa54189270c22/scikit_hep_testdata-0.4.2.tar.gz
# tar zxf scikit_hep_testdata-0.4.2.tar.gz 
# find scikit_hep_testdata-0.4.2
scikit_hep_testdata-0.4.2
scikit_hep_testdata-0.4.2/PKG-INFO
scikit_hep_testdata-0.4.2/egg-info
scikit_hep_testdata-0.4.2/setup.cfg
```

**Comment by henryiii** [comment]
Actually, I think it might be a damaged tarball - I get "decompression failed".

**Comment by henryiii** [comment]
Should be fixed and released!

**Comment by henryiii** [comment]
Huge thanks for this! No one really uses the SDist, so we didn't notice it was broken.

**Comment by veprbl** [comment]
It still is missing the data directory, so installing with `SKHEP_DATA=1` doesn't work.

**Comment by veprbl** [comment]
Also, would it make sense to rename it from scikit_hep_testdata to scikit-hep-testdata to match the PyPi package name.

**Comment by henryiii** [comment]
Yes, it should probably use that name. It is too large to upload it to PyPy if you include the data directory in the SDist.

**Comment by henryiii** [comment]
No, I take it back, I believe the normalized name is with the underscores. PyPI is not sensitive to dashes vs. underscores, `pip install scikit-hep-testdata` and `pip install scikit_hep_testdata` both work. https://pypi.org/project/scikit-hep-testdata/ and https://pypi.org/project/scikit_hep_testdata/ both work.
