### ISSUE TITLE
First pip release

### ISSUE THREAD

**Issue by mayou36** [scikit-hep/scikit-hep-testdata#8]
In order for the package to be useful, e.g. having it in a requirements file, it would be nice to have it on pip.

Sure, it's to be extended, but the basis seems to be here.

Are there any plans for this? travis CI auto-deployment? Or what did you have in mind for the release process?

**Comment by benkrikler** [comment]
Yes absolutely, I've been meaning to get to this the last week or so but other things keep getting in the way; I hope to have it up on pypi by early next week.  Setting up proper CI auto-deployment is part of my plan.

**Comment by benkrikler** [comment]
The CI pipeline should be deploying to Pypi automatically now with each tag.  It's failed so far though, and one suggestion was that there needs to be at least one tag of the package on pypi already, so I've manually pushed the first version to pypi: https://pypi.org/project/scikit-hep-testdata/.  I think that's good enough to close this issue, but once we merge #13 I'll check whether auto-deployment is fixed.

**Comment by eduardo-rodrigues** [comment]
Automated deployment is not up and running but I reckon we can close this now since the package is now released on PyPI.

**Comment by eduardo-rodrigues** [comment]
What are your feeling here, @benkrikler ?
