### ISSUE TITLE
Revive uproots .C macros for producing faked data

### ISSUE THREAD

**Issue by benkrikler** [scikit-hep/scikit-hep-testdata#9]
@jpivarski suggests we recover the .C macros which uproot's testing data contained to generate root files with a newer version of ROOT.  This should be simple since I think this is already in the history of the repository.

**Comment by eduardo-rodrigues** [comment]
I'm going to close this task at this point since it's been untouched for 2.5 years. Some macros are available and we can assume that new ones will be (have been) added with new files included in the repo.
